// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdtB1-jsUVAPXDxGa1LOJhmRVORZuTQ_c',
    appId: '1:372759562752:web:99397325a6a1dd8918e6e5',
    messagingSenderId: '372759562752',
    projectId: 'instapplication-bf6b2',
    authDomain: 'instapplication-bf6b2.firebaseapp.com',
    storageBucket: 'instapplication-bf6b2.appspot.com',
    measurementId: 'G-PL8PH5TYZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBldwA80iogMvEs1XhQilozlu_MOn73rG8',
    appId: '1:372759562752:android:2094198e9ae26f5918e6e5',
    messagingSenderId: '372759562752',
    projectId: 'instapplication-bf6b2',
    storageBucket: 'instapplication-bf6b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZmgmbj7RywQzh_HYoHOrhMHnV3aFVXuE',
    appId: '1:372759562752:ios:ece97ea0d956a29318e6e5',
    messagingSenderId: '372759562752',
    projectId: 'instapplication-bf6b2',
    storageBucket: 'instapplication-bf6b2.appspot.com',
    iosClientId: '372759562752-qc2djkdi0ius843nvik1h919dbhs704v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZmgmbj7RywQzh_HYoHOrhMHnV3aFVXuE',
    appId: '1:372759562752:ios:b10c0924a42558d618e6e5',
    messagingSenderId: '372759562752',
    projectId: 'instapplication-bf6b2',
    storageBucket: 'instapplication-bf6b2.appspot.com',
    iosClientId: '372759562752-0rjrpq2skbvr8m1qmj56un5gk6bgnfeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
